### PR TITLE
Allow applying modifiers, clean up code.

### PR DESCRIPTION
**Pull request by rcorre**
This PR consists of a few commits:

- Apply modifiers if no shape keys exist. This is the main feature I was interested in.
- Clean up code. This made it more readable for me, feel free to discard if it isn't helpful.
- Reduce verbosity, only print on error. Blender is a bit noisy, we don't need to spam the console unless it fails.
- Fix `enabled_plugins` in top-level project.

### CODE REVIEW

**Comment by fire** [comment]
You can apply modifiers with shape keys here. https://github.com/V-Sekai/V-Sekai-Blender-tools/tree/main/addons/ApplyModifierForObjectWithShapeKeys

**Comment by fire** [comment]
In my other copy of the code, I use this pattern of creating a string that is json syntax. Using string replace on it, and then json parse it and use the dictionary get on the data.

**Comment by rcorre** [comment]
> You can apply modifiers with shape keys here

Thanks! Though I feel like having both shapekeys and modifiers is pretty rare. Godot 3 has [enough](https://github.com/godotengine/godot/issues/51860) [problems](https://github.com/godotengine/godot/issues/10402) with shapekeys that I've learned to avoid them, so I think it is best to just keep this simple. I _do_ often have modifiers like Mirror which I want applied on export, so it seems nice to have that option on when we can.

**Comment by fire** [comment]
Also I uh.. have a secondary workflow where I convert blend shapes to skeletal animations, but it's a bit obscure :D.

**Comment by fire** [comment]
I also am working in Godot 4, so I'd need to sync these changes to master of this repository. Want to keep them synced.

**Comment by rcorre** [comment]
Would you like me to backport to `main`, or leave that to you? I'm hoping this plugin will be soon be obsolete in Godot 4 with https://github.com/godotengine/godot/pull/54886#pullrequestreview-808509654, right? :crossed_fingers:

**Comment by fire** [comment]
I would appreciate it if you could help me backport to `main,` as you know, Godot Engine 4 alpha has been promised for several months and has my attention.

**Comment by fire** [comment]
I'll merge it in and then test it. Thanks!

**Pull request merged**
