### PR TITLE
Backport export_apply to main.

### PR DESCRIPTION
**Pull request by rcorre**
- Apply modifiers if no shape keys exist.
- Clean up code.
- Reduce verbosity, only print on error.
- Adjust for godot 4.

Backport of #5.

### CODE REVIEW

**Comment by rcorre** [comment]
I'm not sure if this is a bug in Godot or the plugin, but it crashes on closing the editor:

```
#0  Map<StringName, GDScriptFunction*, Comparator<StringName>, DefaultAllocator>::_find (p_key=..., this=0x55556b6936c8) at ./core/templates/map.h:304
#1  Map<StringName, GDScriptFunction*, Comparator<StringName>, DefaultAllocator>::find (p_key=..., this=0x55556b6936c8) at ./core/templates/map.h:598
#2  GDScriptInstance::notification (this=0x55556b591260, p_notification=<optimized out>) at modules/gdscript/gdscript.cpp:1526
#3  0x00005555599869c4 in Object::notification (this=0x5555617c1c40, p_notification=1, p_reversed=<optimized out>) at core/object/object.cpp:849
#4  0x0000555559988e6a in Object::_predelete (this=this@entry=0x5555617c1c40) at core/object/object.cpp:354
#5  predelete_handler (p_object=p_object@entry=0x5555617c1c40) at core/object/object.cpp:1910
#6  0x000055555739f384 in memdelete<EditorSceneFormatImporter> (p_class=0x5555617c1c40) at ./core/os/memory.h:103
#7  Ref<EditorSceneFormatImporter>::unref (this=0x55556b6bce40) at ./core/object/ref_counted.h:221
#8  Ref<EditorSceneFormatImporter>::~Ref (this=0x55556b6bce40, __in_chrg=<optimized out>) at ./core/object/ref_counted.h:233
#9  Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::Element::~Element (this=0x55556b6bce10, __in_chrg=<optimized out>) at ./core/templates/set.h:49
#10 memdelete_allocator<Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::Element, DefaultAllocator> (p_class=0x55556b6bce10) at ./core/os/memory.h:120
#11 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (this=<optimized out>, p_element=0x55556b6bce10) at ./core/templates/set.h:554
#12 0x00005555573a7b14 in Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=<optimized out>, this=0x5555605555d0) at ./core/templates/set.h:547
#13 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x555560514a60, this=0x5555605555d0) at ./core/templates/set.h:553
#14 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x555560514a60, this=0x5555605555d0) at ./core/templates/set.h:547
#15 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x555569382af0, this=0x5555605555d0) at ./core/templates/set.h:552
#16 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x555569382af0, this=0x5555605555d0) at ./core/templates/set.h:547
#17 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x5555603e8fe0, this=0x5555605555d0) at ./core/templates/set.h:553
#18 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::_cleanup_tree (p_element=0x5555603e8fe0, this=0x5555605555d0) at ./core/templates/set.h:547
#19 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::clear (this=0x5555605555d0) at ./core/templates/set.h:680
#20 Set<Ref<EditorSceneFormatImporter>, Comparator<Ref<EditorSceneFormatImporter> >, DefaultAllocator>::~Set (this=0x5555605555d0, __in_chrg=<optimized out>) at ./core/templates/set.h:697
#21 ResourceImporterScene::~ResourceImporterScene (this=0x5555605554d0, __in_chrg=<optimized out>) at editor/import/resource_importer_scene.h:151
#22 0x00005555560001c9 in memdelete<ResourceImporter> (p_class=0x5555605554d0) at ./core/os/memory.h:108
#23 memdelete<ResourceImporter> (p_class=0x5555605554d0) at ./core/os/memory.h:103
#24 Ref<ResourceImporter>::unref (this=0x5555603d49b0) at ./core/object/ref_counted.h:221
#25 Ref<ResourceImporter>::~Ref (this=0x5555603d49b0, __in_chrg=<optimized out>) at ./core/object/ref_counted.h:233
#26 CowData<Ref<ResourceImporter> >::_unref (this=<optimized out>, this=<optimized out>, p_data=0x5555603d4930) at ./core/templates/cowdata.h:218
#27 CowData<Ref<ResourceImporter> >::_unref (this=<optimized out>, p_data=0x5555603d4930) at ./core/templates/cowdata.h:200
#28 0x0000555559642621 in CowData<Ref<ResourceImporter> >::~CowData (this=0x55555c99cab0, __in_chrg=<optimized out>) at ./core/templates/cowdata.h:386
#29 Vector<Ref<ResourceImporter> >::~Vector (this=0x55555c99caa8, __in_chrg=<optimized out>) at ./core/templates/vector.h:263
#30 ResourceFormatImporter::~ResourceFormatImporter (this=0x55555c99c930, __in_chrg=<optimized out>) at core/io/resource_importer.h:38
#31 0x00005555594d82e4 in memdelete<ResourceFormatImporter> (p_class=0x55555c99c930) at ./core/os/memory.h:103
#32 memdelete<ResourceFormatImporter> (p_class=0x55555c99c930) at ./core/os/memory.h:103
#33 Ref<ResourceFormatImporter>::unref (this=0x55555c788310 <resource_format_importer>) at ./core/object/ref_counted.h:221
#34 unregister_core_types () at core/register_core_types.cpp:345
#35 0x0000555555f08ec7 in Main::cleanup (p_force=p_force@entry=false) at main/main.cpp:2864
#36 0x0000555555eca161 in main (argc=2, argv=0x7fffffffdc38) at platform/linuxbsd/godot_linuxbsd.cpp:60
```

**Comment by fire** [comment]
Testing now and the 3.x branch will take a bit of time.

**Comment by fire** [comment]
Thanks.

**Comment by fire** [comment]
Here's my b3 pr https://github.com/V-Sekai/godot-blender/tree/b3

**Pull request merged**
